env:
  global:
  - secure: UjcWrkL0WPLh9f6NIDu++tnbIUL/jxWXrcM+hLpBOBeQM5Dv0l1rFFqY9aNTtvmplPZTHBGt2AI9jWIxtEH3mFvvY75Q9z4v14QmizEs6+nCLaG22uzJ+9ov0ENl79qxCZQzW4df3KSNMsPMBMnYY/uMbIU2WNnAe6TMVUXmUQcNlOqYkZYlpBRanNlOfElkElLiNSr1UN6Y7jZEQKM4jBeFnguP+I7Ja4L7VcQvGcNA/SpHA4tuHN1Veh8uo0iqBnvT3xU6iVGE+FaZTbmRMHbIwl6ZJ61kYXD2C8agWoX4Uco4A4NK1dGvVz8W+GtoEp3xc/89O9LfwMzVTjM3h3e3lLB3C9jhxHgnGw9W8tK+aqoAxmBVg8uNYexK3G5eDoZXL5PMw1EClp1kPrA4pmnxnwu8qFiZLTQj2g6ZxrQ959aDMIFRGJyqWxtMKvUmAo0qL4xDxU7ng9ZQaEhIVqpAN+l8aRAqfhDRDzNOoa/QPOxucJtSwh9iJQYORuLDci/tVK988NoA1VXFm1YrxXFXG4Ov3PjjA4zazCZcf7hOpLbtU66aixlBaZJAtt46AOfx86vlHlALxfo80/lGYF2ak0GHiivxWUxkEULnXQB+HWkXz7543OYOpx/cg+J5m7xzRvIjK9Oiv43LqylUFB3KF+2F55f5ru4yA5QaTJU=
language: ruby
before_install:
- sudo apt-get install -y jq
script:
- "./script.sh"
